version: 2

sources:
  - name: casper_data_raw
    database: casper-code-challenge
    schema: casper_data_raw
    tables: 
      - name: exercises
      - name: patients
      - name: steps
      # below are the sample tables for incremental pipeline
      - name: sample_exercises
      - name: sample_patients
      - name: sample_steps

  - name: casper_data_curated
    database: casper-code-challenge
    schema: casper_data_curated
    tables: 
      - name: exercises_curated
      - name: patients_curated
      - name: steps_curated
      # below are the sample tables for incremental pipeline
      - name: sample_exercise_incremental
      - name: sample_patients_incremental
      - name: sample_steps_incremental